language: java
os: linux
services:
- docker
env:
  global:
  - HXE_VERSION=2.00.036.00.20190223.1
  - 'PASSWORD_FILE_CONTENT=''{"master_password" : "L1qu1base_test"}'''
  - PASSWORD_FILE_NAME=passwords.json
  - secure: T2ZtPSGeZYIjl1cKdhQcGx3bsKDPHp+LOK/gyVp6yDEeD0UX2xJocmg+PgAHivPxh0QVMhbliAYEzJvaFWuslOSGNiU4yflZrIYt3dK675BcBdOQuPFcgfbCbonr7h3p+QvLgB3FLDJnQ8mnnS/0Ozr6wVEADfYS2lAy7SJ518dlzJpl4sXYw5H6uxiPddgBxLGXxSLzylFg+dmdpDPaiV19YS8S6kMcqC4oQuaQ2JFyNxQCa8ptxk1QtvQmP2eDVCN3hSdLsULMum5w2279Xp8G6iN+TCtczxlZ168bX/qaL163sIPlTdbkpB5YKD+Wf2w4gbDoAzOk4cvq+VzyXGcpI/WFlAtQ/2NdusG1f3QTv3B0arsKMqgIe12FmJBKAXZ1khjJ9XdZEKTcV6dWXZ6mXdA9mOBfRpFKUiEO4wJYjqBoJAEO/6iuS3+2AGL2YXKkZoB2mEjbuqaHxA+BMChz/uzAadfLQZIrcVTx/C/a7gQ8ufNRc82dZaMXe0PjeQPnd/zyjoMrAh5KlwjQ17vDvMHDEw3lIQKKCc3gi796ju3OQ1UwZuIC3cymGQsHtdd8+D0AqJpvSQHpUaRvArwgJfnnGUi+ey/MK33al/bORza3llm0y4K3IyaZR8B6e4vDSZcX9SzFbXsS8mwtgJ71n45WRo11LgmJvmxjZXg=
  - secure: KRODQIX0CF53TYtKz+QxISzYendEKEQdpRYwIQTxmKlPmiU8OH87oGjzKqpeqasCLiBEmoMt3WfkTqqy24ZEsDVXVXwvsxyLsCvApIG6WE/ptts1EbU4CKrqo1SUffI9NEAkNuy9WhdFLZ+0NARyMxZanalR0cloKen68YUrerMExmgLYGcIYYwUVd5bZaGiu2RUw7NanO/TR0P0RIS2XrDrh4LiizLjePQhwrsviMfEIbuO+FoH5eVc9BZOSdHfdEcNndTqwX6I5xDHkGJPcjdFSBvmVGnrK5gGpD93v2xy3eGYd29RZLUlb0sopCSQpmFRpFDdIjdGQ83+ZI/Mfxwoq3cXbywpTWzqLwMYaf3dbuqZ2MLkdDS98xj3jr0G23Vo7iXzCDvvBJkiZBxgJaNZ0HgVeg66+/xKod1yrcDXaUGXSPdla660q56eVBw0/m5P05ysrVxnyXvd5h/OJfpIT3emzkOsoMG0h8ESWjuOl0eMkG71JcztnoW/FGD88q1JjZq3aGr56pagiPMe4etMmx34EMBosSeTpqrLG5eGJ2qbr0ngu1ZDO30fGW5CI4yl8Hh2R/ATjQJKDaChnS6j5CE8HUcQ5ikd7XNr9bxT+2apUEM+i/BRAgN+l5y1JPyjPvLu9mbnq3ULiS26FjSNWan0Fh441JVxgpiepko=
before_script:
- mkdir $TRAVIS_BUILD_DIR/HXE
- chmod -R 777 $TRAVIS_BUILD_DIR/HXE
- echo $PASSWORD_FILE_CONTENT > $TRAVIS_BUILD_DIR/HXE/$PASSWORD_FILE_NAME
- chmod 777 $TRAVIS_BUILD_DIR/HXE/$PASSWORD_FILE_NAME
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker pull store/saplabs/hanaexpress:$HXE_VERSION
- docker run -d -p 39013:39013 -p 39015:39015 -p 39017:39017 -p 39041-39045:39041-39045
  -p 1128-1129:1128-1129 -p 59013-59014:59013-59014 -v $TRAVIS_BUILD_DIR/HXE:/hana/mounts
  --ulimit nofile=1048576:1048576 --sysctl kernel.shmmax=1073741824 --sysctl net.ipv4.ip_local_port_range='40000
  60999' --sysctl kernel.shmmni=524288 --sysctl kernel.shmall=8388608 --name HXETravisCI
  store/saplabs/hanaexpress:$HXE_VERSION --passwords-url file:///hana/mounts/$PASSWORD_FILE_NAME
  --agree-to-sap-license
- sleep 10
- "while true; do \n  STARTING_CONTAINERS=`docker ps --filter \"name=HXETravisCI\"
  --format \"{{.Names}} {{.Status}}\" | grep 'health: starting' | wc -l`;\n  echo
  \"Waiting for $STARTING_CONTAINERS HANA container(s) to finish startup\";\n  if
  [ $STARTING_CONTAINERS -ne 1 ]; then\n    break; \n  fi;\n  sleep 5; \ndone"
- docker ps -a
- docker exec HXETravisCI bash -l -c "hdbsql -u SYSTEM -p L1qu1base_test -i 90 -d
  HXE 'CREATE USER LIQUIBASE_TEST PASSWORD L1qu1base_test NO FORCE_FIRST_PASSWORD_CHANGE'"
- docker logout
addons:
  hosts:
  - hxehost
