language: java
os: linux
services:
- docker
env:
  global:
  - HXE_VERSION=2.00.036.00.20190223.1
  - 'PASSWORD_FILE_CONTENT=''{"master_password" : "L1qu1base_test"}'''
  - PASSWORD_FILE_NAME=passwords.json
  - secure: DzqyKPG2bt+lLM8CW+8YvwqwdSOTyPSnx+RsYZY3MH1s9SqGgB7VHkvcTQbwldjYQ7EtxD1B2hKDQM0N59G1giyGs6OwnoIGTeY4j1m0TQToXB6wthM88MjyexnlKoJms3iuT5Rx8vhsCZx8gJoPQhazXQ0EqCK1rmj092fhktH9JfDKITO2jyKDcPZ31hPuuCKstL7aWlgj8fmvnMZCO3MSMUeVQzCOmXoDxJedMSY1fTrNnmtYaW6dTaNCF5/MxNoarzRo3eUdGfOSTBkNy5KzZPzzVYSlUM+mF+F/CmJv1qyBGkRQYqo1aFVMuAINo6NNVRqh9dA0L+jrm66DPnJOPCxFKpYf1+Urd332gWKMnJ1eZ5MGEAD9/4aA5PRnTNmQ7Opln4qQ8X0UnkP1teQchMYlUiBYqu4VIXcwNdjEVR/vJvdEzmJKtE1NE2KiHz1fK67VEeCEFnavO8SxKKpOY+lzAF5x0+gb9Be36xbDlXGn8IDH5POhyQzYLdgCAuYo9RxZkVIBgtpN4EXRel+FOzcpFNUCf+ChkxH6UNRTnYWtvLZ8LaU6BtdP/jpOKX+zeSTLsn7maPrIQ8SToY93GjsjKtGhw0sPedxr8Cr3/b1QAFjUzymK1BsNEKNreMUQ8+3C6GSOecarwU4pY0VBiCR0QHFdjGwO4jXrmrQ=
  - secure: AOGRTXHslEZ6zZjeydtbSYifjH7wO7UdLJBiX/IVukCGEm1txMi8XNzhcG1w3Zyd1JonS2v5ukFR/mWIXfoVQGrg2QCZdg85ntgFPQPM0GY7dyYAtAQ8824VTSrT5fubocsai1SMX29H67lH3dh5icIQXsJ35de7qABn4ZnQWuf3dFLEoIIva8CDIoc5GatykUtmHfaEkutSD7GWvPb6ADFMlYx5gGm1v7mQovU/jtohF4hu4F8K8pilREIsl/sYtCbOKSKTXh7oXcPrkgoVudxJBFSDJcdrvhmIHdVv1EmmumwwR00TU+BGaOLPluM9AG12touOSY2SiObNs+TPpxbGzc4KAhnrwdyGnYHJcPinkcHmNSKMyIi+7PtkUFFny2qvZRn/Z2Cchxi5vzVDxNJM6gI5N+i4OzTcv150JGi6WtnSXlxgJobIsQkvzszDjyulybITBg9zlhDsRlJ9g9eKU7LB1uQ3FtnUlSthix8O+go1QqaDgES+/fvDztXCs9vUZuZegH0wCEf1WOEXwaucrfrNinUIAek/kgQ2Yi/4kVwf1rvA4wDBRUoZGHfiqRlwIMn54aML6E3ink7Ezw81bBLpxe9/zqiqKfNZKHhypH08+yP4QMXyT2ZwR7Q3weDAiviFwKj2i7/i02wnfhhEnimR10ZyWnWhQkomzn4=
before_script:
- mkdir $TRAVIS_BUILD_DIR/HXE
- chmod -R 777 $TRAVIS_BUILD_DIR/HXE
- echo $PASSWORD_FILE_CONTENT > $TRAVIS_BUILD_DIR/HXE/$PASSWORD_FILE_NAME
- chmod 777 $TRAVIS_BUILD_DIR/HXE/$PASSWORD_FILE_NAME
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker pull store/saplabs/hanaexpress:$HXE_VERSION
- docker run -d -p 39013:39013 -p 39015:39015 -p 39017:39017 -p 39041-39045:39041-39045
  -p 1128-1129:1128-1129 -p 59013-59014:59013-59014 -v $TRAVIS_BUILD_DIR/HXE:/hana/mounts
  --ulimit nofile=1048576:1048576 --sysctl kernel.shmmax=1073741824 --sysctl net.ipv4.ip_local_port_range='40000
  60999' --sysctl kernel.shmmni=524288 --sysctl kernel.shmall=8388608 --name HXETravisCI
  store/saplabs/hanaexpress:$HXE_VERSION --passwords-url file:///hana/mounts/$PASSWORD_FILE_NAME
  --agree-to-sap-license
- sleep 10
- "while true; do \n  STARTING_CONTAINERS=`docker ps --filter \"name=HXETravisCI\"
  --format \"{{.Names}} {{.Status}}\" | grep 'health: starting' | wc -l`;\n  echo
  \"Waiting for $STARTING_CONTAINERS HANA container(s) to finish startup\";\n  if
  [ $STARTING_CONTAINERS -ne 1 ]; then\n    break; \n  fi;\n  sleep 5; \ndone"
- docker ps -a
- docker exec HXETravisCI bash -l -c "hdbsql -u SYSTEM -p L1qu1base_test -i 90 -d
  HXE 'CREATE USER LIQUIBASE_TEST PASSWORD L1qu1base_test NO FORCE_FIRST_PASSWORD_CHANGE'"
- docker logout
addons:
  hosts:
  - hxehost
