language: java
os: linux
services:
- docker
env:
  global:
  - HXE_VERSION=2.00.036.00.20190223.1
  - 'PASSWORD_FILE_CONTENT=''{"master_password" : "L1qu1base_test"}'''
  - PASSWORD_FILE_NAME=passwords.json
  - secure: lHff3Un/CAz9UL8JnAPORsD8bibw9V88lh4xz1wrr44t5yZ6ijODzI69lcyZO+0MXb2wrOzStg3SzHMIJy/NmF/PEBl30ktc1YdJ9umTlCj8BldWYkSbTFdtQ4PdXp9iXoWAyedxXvNbetSq6BZKfzaiK//55OVDuJdkjXnpxiUa3IT/OHlfAg1UVTMZ3HjmPMhA0Y7Z9qzjKMMqtlRQUbhm09C4+bCJEH0MdsqnZgS1reB10FRl/J/RA7rbKqXFcdFA7EFrnJrVWuxggg/jsdBmtplE52QsbxbFwWcYmY6LY7o30f8ONz5n1lq7+aCWA9j79LzrepBirPxpweRNKACJRTtkmhrUm0lT6kddrhmbuNnISqKVSdIm5nfshkzEFqqO3NsTQzdqMDTOM/gL2uFnLbWEUgjnapVgahzzIjtY2jK6b3w9NKZQDsUZaiSJ0V5b5MWspTIv7yFFCOLOdkwFga7oZy47/9ZH7HLJvf2VN9d6dxx6Wmiyb3UvwXMQoSF8JBuGe8U8pKP9q6o7Jnaix6NYv1i0hHUqqMpr434f2FYSh71rXzROlbimhj+a4RDsaYpRghgEvMdJcm5Ti3Jxar0X+9cDwh91EYAJLeGHH0vtrB/G6YC+a+GTBS3tYCqCGQB5mQr5d2bPTMsx+g/3emZI2Xi7DwE2uMFQGVg=
  - secure: Dqe4XKIqtrR1LXSwMYgnIbS6P8tTLUn2lTitHUTX6VWXLVLKQRMW0/gyMC6xnYZxhWHkWRcgpLqFq7zDiBGyANk0hn5ATrVsDSsoMMsFzIYxmrFMpPXMhmFLrtWSU8IS4hwEXx44X2QPpy2q4V22qzk02tf1fOxLdE0g9LClM533EqIWTO+roQxjk/y66hc72RFHsq8niiMwUjqF/O3BkvyDDmLPoZ3OWsRHPerrMMu5dueldRL6UyYAjHkj1Z4VHNKOkAO1I7IJDxwiGRTLQ11NfGWwlcQvoGYtcTKFKic838rugSDe8Q3osbOa7+IdUHO0Uub5RufLt9iBBx3JW5OXyta4FkiSkVxDnNXyhLJHghNRdIdpiFTci7H8CuoFFBBEB71bIUeETsr9mVr57ajupHmlObhROIpysntJfoE8iENrRsUotDNEERmpltYp5M/Z0DqWL+vM3R2Jhg7BtbkoxdQkREJMSf2JqJQkW+B8n5NEEuZ6uat16NB80PbFmjE1TUnXjkyto9BTXyR+iBw5CysD2X8I0OzWBj0TBWIFAuRqogKxBFgPK08aff33P7Znk7223wGjulUEZciT4JkMgVohjRJrbVwMeaY/7vtcUcRUt8hvC3M2SEGq9tXmagKScdw1lpsGnxzArFgHxALWnEuBJNF56mIRJKnct/M=
before_script:
- mkdir $TRAVIS_BUILD_DIR/HXE
- chmod -R 777 $TRAVIS_BUILD_DIR/HXE
- echo $PASSWORD_FILE_CONTENT > $TRAVIS_BUILD_DIR/HXE/$PASSWORD_FILE_NAME
- chmod 777 $TRAVIS_BUILD_DIR/HXE/$PASSWORD_FILE_NAME
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker pull store/saplabs/hanaexpress:$HXE_VERSION
- docker run -d -p 39013:39013 -p 39015:39015 -p 39017:39017 -p 39041-39045:39041-39045
  -p 1128-1129:1128-1129 -p 59013-59014:59013-59014 -v $TRAVIS_BUILD_DIR/HXE:/hana/mounts
  --ulimit nofile=1048576:1048576 --sysctl kernel.shmmax=1073741824 --sysctl net.ipv4.ip_local_port_range='40000
  60999' --sysctl kernel.shmmni=524288 --sysctl kernel.shmall=8388608 --name HXETravisCI
  store/saplabs/hanaexpress:$HXE_VERSION --passwords-url file:///hana/mounts/$PASSWORD_FILE_NAME
  --agree-to-sap-license
- sleep 10
- "while true; do \n  STARTING_CONTAINERS=`docker ps --filter \"name=HXETravisCI\"
  --format \"{{.Names}} {{.Status}}\" | grep 'health: starting' | wc -l`;\n  echo
  \"Waiting for $STARTING_CONTAINERS HANA container(s) to finish startup\";\n  if
  [ $STARTING_CONTAINERS -ne 1 ]; then\n    break; \n  fi;\n  sleep 5; \ndone"
- docker ps -a
- docker exec HXETravisCI bash -l -c "hdbsql -u SYSTEM -p L1qu1base_test -i 90 -d
  HXE 'CREATE USER LIQUIBASE_TEST PASSWORD L1qu1base_test NO FORCE_FIRST_PASSWORD_CHANGE'"
- docker logout
addons:
  hosts:
  - hxehost
