name: Dependabot auto-merge

on:
  workflow_run:
    workflows: ["Build & Test"]
    types:
      - completed

jobs:
  merge-me:
    name: Dependabot automerge
    runs-on: ubuntu-latest

    steps:
      - name: Automerge dependabot issue
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
